
import javax.swing.JOptionPane;
import java.util.List;
import java.util.jar.Attributes.Name;   //nieuzywane

import repositories.impl.DummyDb;
import repositories.impl.DummyRepositoryCatalog;



import Domain.*;
import repositories.*;
import repositories.impl.*;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;


public class Main {

	public static void main(String[] args) {
		
		
		Person jnowak = new Person();
		jnowak.setName("Adam");
		jnowak.setSurname("Urbanow");
		String url="jdbc:hsqldb:hsql://localhost/cmentarz";
		try {
		Connection connection = DriverManager.getConnection(url);
		/*
		String createUserTable=
		"CREATE TABLE users("
		+ "id int GENERATED BY DEFAULT AS IDENTITY,"
		+ "login VARCHAR(20),"
		+ "password VARCHAR(20)"
		+ ")";
		Statement stmt = connection.createStatement();
		stmt.executeUpdate(createUserTable);
		*/
		IRepository<Person> person = new PersonRepository(connection);
		person.add(jnowak);
		List<Person> personfromDb = person.getAll();
		for(Person fromDb : personfromDb)
		System.out.println(fromDb.getId()+" "+fromDb.getName()+" "+fromDb.getSurname());
		Person Adam = person.get(2);
		Adam.setSurname("urrrban");
		person.update(Adam);
		Person toDelete = personfromDb.get(0);
		person.delete(toDelete);
		for(Person fromDb : person.getAll())
		System.out.println(fromDb.getId()+" "+fromDb.getName()+" "+fromDb.getSurname());
		} catch (SQLException e) {
		e.printStackTrace();
		}
		System.out.println("Koniec");
		}
		}